apiVersion: deployment.com.ebay.cassini.tess.controllers/v1alpha1
kind: MatrixDeployment
metadata:
  name: prod-rno-completed-1-qry
  namespace: cassini-native
spec:
  colo: rno
  columns: 2
  component: qry
  containerVersions:
    dbus: 18.04-v1
    logpusher: 1.0.alpine3.8
    monitor-cron: "18.04"
    monitor-exporter: "18.04"
    qss: 18.04-v2
  dataPackages:
  - buildTime: "2019063021"
    sourceColo: HUYGENSLVS
    type: item_seller
    version: 34.8.878_hdp
  - buildTime: "2019012316"
    sourceColo: SLC
    type: codebooks
    version: 1.0.1541545744_013
  - buildTime: "2019022523"
    sourceColo: SLC
    type: shipping
    version: 1.0.2019022523
  - buildTime: "2019032522"
    sourceColo: HUYGENS
    type: mlrmodels
    version: 0.10.6622
  poolOrdinal: "1"
  realm: prod
  rows: 3
  usecase: completed