cassinfra:
  CASSINFRA_ROOT: /ebay/cassinfra3
  CASSINFRA_BACKUP: /ebay/backups/cassinfra3
database:
  host: 192.168.1.11
  port: 3306
  user: root
  password: 1234567
  name: searchops
  auto_commit: false
cms:
  url: https://armt.vip.ebay.com/ar/soa/consumer/
  userid: _UDNS_MIT
  token_file: _udns_mit.token