cassinfra:
  cassinfra_root: /ebay/cassinfra3
  cassinfra_backup: /ebay/backups/cassinfra3
database:
  host: 192.168.1.11
  port: 3306
  user: root
  password: 1234567
  database: searchops
cms:
  url: https://armt.vip.ebay.com/ar/soa/consumer/
  userid: _UDNS_MIT
  token_file: _udns_mit.token
  users:
    - 1
    - 2
    - 3
    - 4
    - 5